"""initial_schema

Revision ID: 2208f532cb07
Revises: 
Create Date: 2026-04-24 14:48:39.842899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2208f532cb07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condominios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('rut_comunidad', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('plan_suscripcion', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut_comunidad')
    )
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_roles',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_id', 'rol_id')
    )
    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.Column('numero_parcela', sa.String(), nullable=False),
    sa.Column('propietario_nombre', sa.String(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auditoria_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('detalles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boletas_maestras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.Column('periodo_mes', sa.Date(), nullable=False),
    sa.Column('url_imagen_boleta', sa.String(), nullable=True),
    sa.Column('boleta_visible_usuarios', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('lecturas_cerradas', sa.Boolean(), nullable=False),
    sa.Column('liquidaciones_cerradas', sa.Boolean(), nullable=False),
    sa.Column('total_kwh_compania', sa.Float(), nullable=True),
    sa.Column('monto_neto_electricidad_consumida', sa.Float(), nullable=True),
    sa.Column('monto_total_emision', sa.Integer(), nullable=True),
    sa.Column('monto_saldo_anterior', sa.Integer(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_parcelas',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'parcela_id')
    )
    op.create_table('boleta_items_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boleta_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('monto_neto_clp', sa.Float(), nullable=False),
    sa.Column('tipo_calculo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['boleta_id'], ['boletas_maestras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecturas_parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.Column('boleta_id', sa.Integer(), nullable=False),
    sa.Column('lectura_anterior', sa.Float(), nullable=False),
    sa.Column('lectura_actual', sa.Float(), nullable=False),
    sa.Column('kwh_consumidos', sa.Float(), nullable=False),
    sa.Column('lector_id', sa.Integer(), nullable=False),
    sa.Column('fecha_toma', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['boleta_id'], ['boletas_maestras.id'], ),
    sa.ForeignKeyConstraint(['lector_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidaciones_parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.Column('boleta_id', sa.Integer(), nullable=False),
    sa.Column('monto_energia_kwh', sa.Integer(), nullable=True),
    sa.Column('monto_prorrateo_variable', sa.Integer(), nullable=True),
    sa.Column('monto_cuota_fija', sa.Integer(), nullable=True),
    sa.Column('total_pagar_mes', sa.Integer(), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['boleta_id'], ['boletas_maestras.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liquidaciones_parcelas')
    op.drop_table('lecturas_parcelas')
    op.drop_table('boleta_items_detalle')
    op.drop_table('usuario_parcelas')
    op.drop_table('boletas_maestras')
    op.drop_table('auditoria_logs')
    op.drop_table('usuarios')
    op.drop_table('parcelas')
    op.drop_table('menu_roles')
    op.drop_table('roles')
    op.drop_table('menus')
    op.drop_table('condominios')
    # ### end Alembic commands ###
