"""rifas_solidarias

Revision ID: efa24b43f91a
Revises: 2208f532cb07
Create Date: 2026-10-02 18:04:14.075246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'efa24b43f91a'
down_revision: Union[str, None] = '2208f532cb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rifas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('beneficiario', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_numero', sa.Integer(), nullable=False),
    sa.Column('cantidad_numeros', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cerrada_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rifas_condominio_id'), 'rifas', ['condominio_id'], unique=False)
    op.create_table('cobros_rifa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rifa_id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_numeros', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.ForeignKeyConstraint(['rifa_id'], ['rifas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rifa_id', 'parcela_id', name='uq_cobro_rifa_parcela')
    )
    op.create_table('compras_rifa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rifa_id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('registrada_por_admin', sa.Boolean(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('anulada', sa.Boolean(), nullable=False),
    sa.Column('anulada_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulada_por_id', sa.Integer(), nullable=True),
    sa.Column('numeros', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['anulada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.ForeignKeyConstraint(['rifa_id'], ['rifas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_rifa_parcela_id'), 'compras_rifa', ['parcela_id'], unique=False)
    op.create_index(op.f('ix_compras_rifa_rifa_id'), 'compras_rifa', ['rifa_id'], unique=False)
    op.create_table('rifa_numeros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('rifa_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compras_rifa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rifa_id'], ['rifas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rifa_id', 'numero', name='uq_rifa_numero')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rifa_numeros')
    op.drop_index(op.f('ix_compras_rifa_rifa_id'), table_name='compras_rifa')
    op.drop_index(op.f('ix_compras_rifa_parcela_id'), table_name='compras_rifa')
    op.drop_table('compras_rifa')
    op.drop_table('cobros_rifa')
    op.drop_index(op.f('ix_rifas_condominio_id'), table_name='rifas')
    op.drop_table('rifas')
    # ### end Alembic commands ###
